Name: Aniruddh Kulkarni

Roll No : I081

Batch : I3

Program : B.Tech CS (AI)

Semester : IInd Semester

Date of Experiment : 14-04-21

A.1 Aim:  To study Arrays and NumPy Arrays in python.

Task 1:  
Write a Python program to reverse an array without using an in-built function.


In [ ]:
import numpy as np
array = np.array([1,2,3,4])
reversed = []
for i in range(len(array),0,-1):
  reversed.append(i)
reversed

[4, 3, 2, 1]

Task 2:  
Write a Python program to find the frequency of a user given number in an array.(without using an in-built function)


In [ ]:
arr = ar.array("i",[1,2,3,2,2,5,1])
count = 0
x = int(input("Enter a number you would like to check:"))
for i in arr:
  if i==x:
    count = count +1
print("The number",x,"is there",count,"number of times")
  

Enter a number you would like to check:2
The number 2 is there 3 number of times


Task 3:  

Write a Python program to place all negative numbers in the array at the end of the array and  positive numbers in the beginning.

In [ ]:
arr = np.array([-1,4,-6,3,2,-5,5])
k = np.sort(arr)
for i in range(0, len(k)):    
    print(end = ""),     
print("Array in reverse order: ");    
for i in range(len(k)-1, -1, -1):     
    print(k[i],end = " ")

Array in reverse order: 
5 4 3 2 -1 -5 -6 

Task 4:   

Write a Python program to sort an array in wave form. 

Example :  

Input: A[] = {2, 4, 6, 8, 10, 20} 

Output: A[] = {4, 2, 8, 6, 20, 10} 

In [ ]:
def waveform(arr,n):
  np.sort(arr)
  for i in range(0,n-1,2):
    arr[i],arr[i+1] = arr[i+1],arr[i]
arr = np.array([2,4,6,8,10,20])
waveform(arr,len(arr))
print(arr)

[ 4  2  8  6 20 10]


Task 5 :  

Write a Python program to print a given matrix in spiral form. 

Example :  

A = [[1 2 3] 

     [4 5 6] 

     [7 8 9]] 

Spiral form : 1 2 3 6 9 8 7 4 5 

In [ ]:
import numpy as np


a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.array([[1,2],[3,4]])


def spiral(r,c,a):
    row = 0
    col = 0
    #if (r%2 is not 0):
     #       temp = a[r//2][c//2]
    while True:
        for i in range (col , c-1):
            print(a[row][i] , end = ' ')
            
        for i in range (row , r-1):
            print(a[i][c-1] , end = ' ')
            
        for i in range (c-1 , col , -1):
            print(a[r-1][i] , end = ' ')
            
        for i in range(r-1, row , -1):
            print(a[i][col] , end = ' ')
        
        row+=1
        col+=1
        r-=1
        c-=1
        
        if (r<-1):
         #   print(temp)
            break
    
print(a)
spiral(4,4,a)
print('\n',b)
spiral(3,3,b)
print('\n',c)
spiral(2,2,c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 3 6 9 8 7 4 
 [[1 2]
 [3 4]]
1 2 4 3 

Task 6 :  

6.1 	Write a Python program to print ‘k’ smallest element in an unsorted array. 

6.2 	Write aPython program to print ‘k’ largest element in an unsorted array.

In [ ]:
def largest(arr,n):
  largest = arr[0]
  for i in arr:
    if(i>largest):
      largest = i
  return largest
def smallest(arr,n):
  smallest = arr[0]
  for i in arr:
    if i<smallest:
      smallest = i
  return smallest
arr = np.array([2,-1,4,3,6,7])
print("Largest:",largest(arr,len(arr)))
print("Smallest:",smallest(arr,len(arr)))

Largest: 7
Smallest: -1


Task 7: 

Write a Python Program to add two 3x3 Matrices using Nested Loop. 

In [ ]:
x = [[12,2,3],
    [46 ,54,68],
    [8 ,8,9]]
y = [[3,11,3],
    [6,5,9],
    [43,5,76]]
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
for i in range(len(x)):
   for j in range(len(x[0])):
       result[i][j] = x[i][j] + y[i][j]
for r in result:
   print(r)

[15, 13, 6]
[52, 59, 77]
[51, 13, 85]


Task 8: 

Write a Python Program to multiply two Matrices using Nested Loop. 

In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[3,4],[5,6]]) 
product = np.zeros((2,2),int)
for i in range(2):
  for j in range(2):
    for v in range(2):
      product[i,j] += a1[i,v]*a2[v,j]
print(product)

[[13 16]
 [29 36]]


Task 9: 

Write a Python Program to Calculate the sum of all columns in a 2D NumPy array 

Example :   

A = [ [1 2 3] 

 	[1 1 1] 

 	[1 1 1]] 

 

Column wise Sum: 3 4 5 

In [ ]:
a = np.array(([1,2,3],[1,1,1],[1,1,1]),int)
print(a)
sum = np.sum(a,axis = 0)                                                                        #axis = 0 means column 1 means row
print("Column wise sum:",sum)

[[1 2 3]
 [1 1 1]
 [1 1 1]]
Column wise sum: [3 4 5]


Task 10: 

Write a Python Program to find Range and Coefficient of range of Array. 

Range = Max – Min 

Coefficient of Range = (Max – Min) / (Max + Min) 

Example :  

A = [10, 20, 30, 5, 8] 

Range : 25 

Coefficient of Range : 0.7142857142857143 

In [ ]:
a = np.array([35,23,32,25,8])
Range = np.max(a)-np.min(a) #Can also use np.ptp(A) 
print("Range:",Range)
other_thing = np.max(a)+np.min(a)
cor = Range/other_thing
print("Coeddicient of Range:",cor)

Range: 27
Coeddicient of Range: 0.627906976744186
